name: Stg-Data-Migration-$(rev:r)
trigger:
  batch: true
  branches:
    include:
    - staging
  paths:
    include:
    - .ado/workflows/data_migration/dataMigrationPipelineStg.yml
    - data_onetime_migration/**
variables:
- name: destinationPath
  value: synhdq
- name: sourcePath
  value: data_onetime_migration
steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: IEP-LANDING-STG-AzureDevOpsPipelineSP
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: az storage blob upload-batch --auth-mode login -d $(destinationPath)/git --account-name "iepdlz01stgraw" -s "$(System.DefaultWorkingDirectory)/$(sourcePath)/" --overwrite

